/*****
Purpose: Determine the response time after an addition of salt to the fish tank
*****/

// constants won't change
const int solenoidPowPin = 3;  // Pin that triggers solenoid
const int readPin = 0;  // Pin for salinity sensor
const int setUpTime = 5; // Extra time in seconds to set up physical test before salt is added starts
const int openTime = 1; // number of seconds to open solenoid

// int values that will be updated
int salinity;

// float values
float startTime, currentTime;

void setup() {
Serial.begin(9600);
pinMode(solenoidPowPin, OUTPUT);
startTime = millis()/1000.0; 
}

void loop()
{
currentTime = millis()/1000.0; // Current time in seconds

if (currentTime - startTime >= setUpTime & currentTime - startTime <= setUpTime + openTime) // Open solenoid for set time
 {
  digitalWrite(solenoidPowPin,HIGH);
 }
 else
  {
  digitalWrite(solenoidPowPin,LOW);
  }

salinity = analogRead(0); // Take salinity reading


Serial.print("Switch state = ");
Serial.print(digitalRead(solenoidPowPin));Serial.print(", ");
Serial.print("Time = "); Serial.print(currentTime); Serial.print(", ");
Serial.print("Salinity = "); Serial.println(salinity); //This variable should probably be generated by your 'salinity read' function
}


